# Generated by Django 2.0 on 2017-12-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beeps', '0003_auto_20171209_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beep',
            options={'ordering': ['-timestamp']},
        ),
    ]
