# Generated by Django 2.0 on 2017-12-11 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beeps', '0004_auto_20171211_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='beep',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beeps.Beep'),
        ),
    ]
